export const dummyData = [{
    title: 'Bread', image: require('./assets/bread.png'),
    category: [{ title: 'Britannia Whole Wheat', image: require('./assets/bread1.png'), desc: 'Brown Bread', price: 50, qantity: '250 Gms' },
    { title: 'Britannia Brown Bread ', image: require('./assets/bread2.png'), desc: ' Brown Bread', price: 50, qantity: '250 Gms' },
    { title: 'Britannia Aata Bread', image: require('./assets/bread3.png'), desc: ' tingredients, soft and fresh loaded', price: 50, qantity: '250 Gms' },
    { title: 'Britannia Aata Bread', image: require('./assets/bread.png'), desc: 'Atta bread is made from the choicest ingredients, soft and fresh loaded', price: 50, qantity: '250 Gms' },
    { title: 'Britannia Aata Bread', image: require('./assets/bread.png'), desc: 'Atta bread is made from the choicest ingredients, soft and fresh loaded', price: 50, qantity: '250 Gms' },
    { title: 'Britannia Aata Bread', image: require('./assets/bread.png'), desc: 'Atta bread is made from the choicest ingredients, soft and fresh loaded', price: 50, qantity: '250 Gms' }]
},
{
    title: 'Chocklate', image: require('./assets/chocklate.png'),
    category: [{ title: 'Britannia Whole Wheat', image: require('./assets/bread1.png'), desc: 'Brown Bread', price: 50, qantity: '250 Gms' },
    { title: 'chocklate1 ', image: require('./assets/chocklate1.png'), desc: ' chocko', price: 50, qantity: '250 Gms' },
    { title: 'chocklate2', image: require('./assets/chocklate2.png'), desc: ' tingredients, soft and fresh loaded', price: 50, qantity: '250 Gms' },
    { title: 'chocklate3', image: require('./assets/chocklate3.png'), desc: 'Atta bread is made from the choicest ingredients, soft and fresh loaded', price: 50, qantity: '250 Gms' },
    { title: 'chocklate4 Aata Bread', image: require('./assets/chocklate4.png'), desc: 'Atta bread is made from the choicest ingredients, soft and fresh loaded', price: 50, qantity: '250 Gms' },
    ]
},
{ title: 'Grains', image: require('./assets/grains.png') ,
category: [{ title: 'Britannia Whole Wheat', image: require('./assets/grains1.png'), desc: 'Brown Bread', price: 50, qantity: '250 Gms' },
{ title: 'chocklate1 ', image: require('./assets/grains2.png'), desc: ' chocko', price: 50, qantity: '250 Gms' },
{ title: 'chocklate2', image: require('./assets/grains3.png'), desc: ' tingredients, soft and fresh loaded', price: 50, qantity: '250 Gms' },
{ title: 'chocklate3', image: require('./assets/grains4.png'), desc: 'Atta bread is made from the choicest ingredients, soft and fresh loaded', price: 50, qantity: '250 Gms' },
{ title: 'chocklate4 Aata Bread', image: require('./assets/grains1.png'), desc: 'Atta bread is made from the choicest ingredients, soft and fresh loaded', price: 50, qantity: '250 Gms' },
]},

{ title: 'Vegetables', image: require('./assets/vegetable.png'),
category: [{ title: 'Britannia Whole Wheat', image: require('./assets/vegetable1.png'), desc: 'Brown Bread', price: 50, qantity: '250 Gms' },
{ title: 'chocklate1 ', image: require('./assets/vegetable2.png'), desc: ' chocko', price: 50, qantity: '250 Gms' },
{ title: 'chocklate2', image: require('./assets/vegetable3.png'), desc: ' tingredients, soft and fresh loaded', price: 50, qantity: '250 Gms' },
{ title: 'chocklate3', image: require('./assets/vegetable4.png'), desc: 'Atta bread is made from the choicest ingredients, soft and fresh loaded', price: 50, qantity: '250 Gms' },
{ title: 'chocklate4 Aata Bread', image: require('./assets/vegetable1.png'), desc: 'Atta bread is made from the choicest ingredients, soft and fresh loaded', price: 50, qantity: '250 Gms' },
] }, 
{ title: 'Fruits', image: require('./assets/fruits.png'),
category: [{ title: 'Britannia Whole Wheat', image: require('./assets/fruits1.png'), desc: 'Brown Bread', price: 50, qantity: '250 Gms' },
{ title: 'chocklate1 ', image: require('./assets/fruits2.png'), desc: ' chocko', price: 50, qantity: '250 Gms' },
{ title: 'chocklate2', image: require('./assets/fruits3.png'), desc: ' tingredients, soft and fresh loaded', price: 50, qantity: '250 Gms' },
{ title: 'chocklate3', image: require('./assets/fruits4.png'), desc: 'Atta bread is made from the choicest ingredients, soft and fresh loaded', price: 50, qantity: '250 Gms' },
{ title: 'chocklate4 Aata Bread', image: require('./assets/fruits4.png'), desc: 'Atta bread is made from the choicest ingredients, soft and fresh loaded', price: 50, qantity: '250 Gms' },
]},
 { title: 'Cake', image: require('./assets/cake.png'),
 category: [{ title: 'Britannia Whole Wheat', image: require('./assets/cake1.png'), desc: 'Brown Bread', price: 50, qantity: '250 Gms' },
    { title: 'chocklate1 ', image: require('./assets/cake2.png'), desc: ' chocko', price: 50, qantity: '250 Gms' },
    { title: 'chocklate2', image: require('./assets/cake3.png'), desc: ' tingredients, soft and fresh loaded', price: 50, qantity: '250 Gms' },
    { title: 'chocklate3', image: require('./assets/cake4.png'), desc: 'Atta bread is made from the choicest ingredients, soft and fresh loaded', price: 50, qantity: '250 Gms' },
    { title: 'chocklate4 Aata Bread', image: require('./assets/cake1.png'), desc: 'Atta bread is made from the choicest ingredients, soft and fresh loaded', price: 50, qantity: '250 Gms' },
    ] }]
